import Foundation

struct QuestionItem: Identifiable {
    let id       : Int
    let category : String
    let title    : String
    let subtitle : String?
    let points   : [String]
    let tip      : String?
}

// MARK: - Partner path questions (translated from questions.dart)

let kPartnerQuestions: [QuestionItem] = [
    QuestionItem(id: 1, category: "行为变化与异常", title: "最近回家时间明显变晚了吗？",
        subtitle: "时间异常",
        points: ["频繁加班但无法核实", "借口朋友聚餐但说不清细节", "回家后情绪低落或亢奋"],
        tip: "注意是否伴随手机使用频率异常升高"),
    QuestionItem(id: 2, category: "行为变化与异常", title: "对你的关注或亲密行为明显减少了吗？",
        subtitle: "情感疏离",
        points: ["主动交流减少", "肢体接触回避", "对你的问题敷衍回答"],
        tip: nil),
    QuestionItem(id: 3, category: "行为变化与异常", title: "外表打扮或个人卫生习惯突然改变了吗？",
        subtitle: "外貌变化",
        points: ["开始使用新香水或护肤品", "健身频率突然增加", "对穿着打扮变得异常在意"],
        tip: "尤其关注出门前的额外准备"),
    QuestionItem(id: 4, category: "行为变化与异常", title: "是否对某人或某话题变得格外敏感或回避？",
        subtitle: "话题回避",
        points: ["提到某个名字时明显情绪变化", "主动转移话题", "发火或表现出防御性反应"],
        tip: nil),
    QuestionItem(id: 5, category: "行为变化与异常", title: "最近是否情绪波动异常，喜怒无常？",
        subtitle: "情绪波动",
        points: ["无故发脾气", "突然变得极度体贴后又冷漠", "有时陷入沉思或走神"],
        tip: nil),
    QuestionItem(id: 6, category: "社交与聊天痕迹", title: "是否频繁使用手机，且对你隐瞒屏幕内容？",
        subtitle: "手机异常",
        points: ["将手机翻转或随身携带进卫生间", "收到消息立即删除", "单独设立陌生应用或隐藏文件夹"],
        tip: "注意深夜频繁震动或静音后独自查看"),
    QuestionItem(id: 7, category: "社交与聊天痕迹", title: "是否设置了新密码或更改了手机/账号密码？",
        subtitle: "账号锁定",
        points: ["更改了你曾知道的密码", "新增指纹或面容ID排除你", "拒绝共享位置或云端相册"],
        tip: nil),
    QuestionItem(id: 8, category: "社交与聊天痕迹", title: "是否频繁与某个你不熟悉的人联系？",
        subtitle: "陌生联系人",
        points: ["通话记录中反复出现同一号码", "微信/WhatsApp与某人高频互动", "对此人身份解释含糊"],
        tip: nil),
    QuestionItem(id: 9, category: "社交与聊天痕迹", title: "是否在你面前接听电话时走开或压低声音？",
        subtitle: "通话回避",
        points: ["接电话必须离开房间", "挂断后解释不合理", "声称是工作电话但时间异常"],
        tip: nil),
    QuestionItem(id: 10, category: "社交与聊天痕迹", title: "微信/通讯软件聊天记录是否经常被清空？",
        subtitle: "记录清除",
        points: ["定期清空对话记录", "特定联系人聊天始终为空", "开启了自动删除功能"],
        tip: nil),
    QuestionItem(id: 11, category: "消费与地址痕迹", title: "是否有不明来源的消费记录或现金流动？",
        subtitle: "消费异常",
        points: ["出现陌生平台或场所的消费", "大额现金取款无法解释", "礼品、餐厅等消费未对你提及"],
        tip: "可查看支付宝/微信账单明细"),
    QuestionItem(id: 12, category: "消费与地址痕迹", title: "是否购买过你不知情的礼物或奢侈品？",
        subtitle: "礼物异常",
        points: ["包装袋或盒子来历不明", "快递收货与消费时间吻合", "物品与你的偏好不符"],
        tip: nil),
    QuestionItem(id: 13, category: "消费与地址痕迹", title: "是否拒绝分享位置或位置信息经常与描述不符？",
        subtitle: "位置不符",
        points: ["拒绝开启位置共享", "说在A地但定位显示B地", "事后解释前后矛盾"],
        tip: nil),
    QuestionItem(id: 14, category: "行程与位置痕迹", title: "是否有频繁且不明原因的外出或出差？",
        subtitle: "行程异常",
        points: ["突然增加出差频率", "临时外出无法说明去向", "出差细节无法核实"],
        tip: nil),
    QuestionItem(id: 15, category: "行程与位置痕迹", title: "车里是否出现了你不认识的物品或异常痕迹？",
        subtitle: "车辆痕迹",
        points: ["陌生的饮料杯或餐巾纸", "座椅位置或后视镜被调整", "车内异常香水味"],
        tip: nil),
    QuestionItem(id: 16, category: "行程与位置痕迹", title: "是否有你无法联系上的空白时间段？",
        subtitle: "失联时段",
        points: ["特定时间段手机无人接听", "事后解释手机没电或没信号", "行踪与说法对不上"],
        tip: nil),
    QuestionItem(id: 17, category: "应用与设备痕迹", title: "手机中是否有你不了解的陌生App？",
        subtitle: "陌生应用",
        points: ["隐藏或伪装成其他名称的应用", "私密相册或加密通讯软件", "应用使用时间与你在一起时不符"],
        tip: nil),
    QuestionItem(id: 18, category: "应用与设备痕迹", title: "是否频繁使用私人浏览模式或清除浏览记录？",
        subtitle: "浏览痕迹",
        points: ["浏览器历史始终为空", "主动使用无痕模式", "阻止你查看搜索记录"],
        tip: nil),
    QuestionItem(id: 19, category: "应用与设备痕迹", title: "是否有其他你不知情的社交媒体账号或小号？",
        subtitle: "隐藏账号",
        points: ["出现陌生平台登录记录", "发现与主账号风格不同的内容", "朋友圈或主页对你隐藏"],
        tip: nil),
    QuestionItem(id: 20, category: "短视频与社交平台痕迹", title: "是否在短视频平台或社交媒体上与陌生人私下互动？",
        subtitle: "平台互动",
        points: ["私信往来频繁且内容被隐藏", "点赞收藏记录刻意清除", "深夜频繁刷特定账号内容"],
        tip: nil),
]

// MARK: - Self path questions (translated from questions_self.dart)

let kSelfQuestions: [QuestionItem] = [
    QuestionItem(id: 1, category: "情感与吸引力", title: "你是否对伴侣以外的某人产生了强烈的情感吸引？",
        subtitle: nil,
        points: ["频繁想到对方", "见面时有特殊的紧张或期待感", "对方不在时感到失落"],
        tip: nil),
    QuestionItem(id: 2, category: "情感与吸引力", title: "你是否开始将伴侣与这个人进行比较？",
        subtitle: nil,
        points: ["在心里暗自比较两人的优缺点", "觉得对方在某方面更符合你的理想", "开始对伴侣的缺点更加敏感"],
        tip: nil),
    QuestionItem(id: 3, category: "行为与互动", title: "你是否主动寻找机会与这个人独处或增加接触？",
        subtitle: nil,
        points: ["制造借口单独见面", "频繁发起聊天或联系", "在社交场合特意靠近对方"],
        tip: nil),
    QuestionItem(id: 4, category: "行为与互动", title: "你们之间是否有过身体上的亲密接触？",
        subtitle: nil,
        points: ["超越普通朋友的拥抱或触碰", "接吻或更进一步的行为", "即使只是\"意外\"的肢体接触"],
        tip: nil),
    QuestionItem(id: 5, category: "隐瞒与欺骗", title: "你是否对伴侣隐瞒了与这个人的联系或见面？",
        subtitle: nil,
        points: ["删除聊天记录或通话记录", "撒谎说自己在别处", "刻意在伴侣面前不提这个人"],
        tip: nil),
    QuestionItem(id: 6, category: "隐瞒与欺骗", title: "你是否专门为与这个人的互动创建了隐私保护？",
        subtitle: nil,
        points: ["新建了隐藏应用或单独账号", "设置了特殊密码或通知屏蔽", "用暗号或昵称来称呼对方"],
        tip: nil),
    QuestionItem(id: 7, category: "情感投入", title: "你是否与这个人分享了不会告诉伴侣的秘密或内心想法？",
        subtitle: nil,
        points: ["倾诉了对感情不满或对伴侣的抱怨", "分享了自己的梦想或脆弱的一面", "觉得对方比伴侣更懂你"],
        tip: nil),
    QuestionItem(id: 8, category: "情感投入", title: "你是否开始对这段关系产生了幻想或规划？",
        subtitle: nil,
        points: ["想过如果和对方在一起会怎样", "幻想过两人的未来", "开始考虑是否要结束现有感情"],
        tip: nil),
]
